services:
  scraper:
    build: .
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: example
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: analysis-dev
  db:
    image: postgres
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: analysis-dev
    volumes:
      - pgdata:/var/lib/postgresql/data_sources
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
volumes:
  pgdata:
